services:
  - type: web
    name: linkedin-req-sender
    env: python
    buildCommand: "./build.sh"
    startCommand: "./start.sh"
    disk:
      name: data-disk
      mountPath: /data
      sizeGB: 1
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: PLAYWRIGHT_BROWSERS_PATH
        value: /opt/render/project/src/pw-browsers
